In [4]:
import pandas as pd

df = pd.read_csv("../Dataset/zomato.csv", encoding="latin1")

df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [5]:
df.shape

(9551, 21)

In [6]:
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='str')

In [7]:
df.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [8]:
country_df = pd.read_excel("../Dataset/country-code.xlsx")

country_df.head()

   Country Code    Country
0             1      India
1            14  Australia
2            30     Brazil
3            37     Canada
4            94  Indonesia

In [9]:
country_df.columns

Index(['Country Code', 'Country'], dtype='str')

In [10]:
df = df.merge(country_df, on="Country Code", how="left")

df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes,Country
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Yes,No,No,No,3,4.8,Dark Green,Excellent,314,Phillipines
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Yes,No,No,No,3,4.5,Dark Green,Excellent,591,Phillipines
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Yes,No,No,No,4,4.4,Green,Very Good,270,Phillipines
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,No,No,No,No,4,4.9,Dark Green,Excellent,365,Phillipines
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Yes,No,No,No,4,4.8,Dark Green,Excellent,229,Phillipines

In [11]:
cuisine_split = df["Cuisines"].str.split(",", expand=True)

cuisine_split.head()

          0          1          2        3    4    5    6    7
0    French   Japanese   Desserts      NaN  NaN  NaN  NaN  NaN
1  Japanese        NaN        NaN      NaN  NaN  NaN  NaN  NaN
2   Seafood      Asian   Filipino   Indian  NaN  NaN  NaN  NaN
3  Japanese      Sushi        NaN      NaN  NaN  NaN  NaN  NaN
4  Japanese     Korean        NaN      NaN  NaN  NaN  NaN  NaN

In [12]:
cuisine_split.columns = [
    f"Cuisine_{i+1}" for i in range(cuisine_split.shape[1])
]

cuisine_split.head()

,Cuisine_1,Cuisine_2,Cuisine_3,Cuisine_4,Cuisine_5,Cuisine_6,Cuisine_7,Cuisine_8
0,French,Japanese,Desserts,NaN,NaN,NaN,NaN,NaN
1,Japanese,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Seafood,Asian,Filipino,Indian,NaN,NaN,NaN,NaN
3,Japanese,Sushi,NaN,NaN,NaN,NaN,NaN,NaN
4,Japanese,Korean,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
cuisine_split = cuisine_split.apply(lambda x: x.str.strip())

cuisine_split.head()

,Cuisine_1,Cuisine_2,Cuisine_3,Cuisine_4,Cuisine_5,Cuisine_6,Cuisine_7,Cuisine_8
0,French,Japanese,Desserts,NaN,NaN,NaN,NaN,NaN
1,Japanese,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Seafood,Asian,Filipino,Indian,NaN,NaN,NaN,NaN
3,Japanese,Sushi,NaN,NaN,NaN,NaN,NaN,NaN
4,Japanese,Korean,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df = pd.concat([df, cuisine_split], axis=1)

df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Votes,Country,Cuisine_1,Cuisine_2,Cuisine_3,Cuisine_4,Cuisine_5,Cuisine_6,Cuisine_7,Cuisine_8
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,314,Phillipines,French,Japanese,Desserts,NaN,NaN,NaN,NaN,NaN
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,591,Phillipines,Japanese,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,270,Phillipines,Seafood,Asian,Filipino,Indian,NaN,NaN,NaN,NaN
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,365,Phillipines,Japanese,Sushi,NaN,NaN,NaN,NaN,NaN,NaN
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,229,Phillipines,Japanese,Korean,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df.shape

(9551, 30)

In [17]:
df[["Cuisines", "Cuisine_1", "Cuisine_2", "Cuisine_3", "Cuisine_4"]].head()

                           Cuisines Cuisine_1 Cuisine_2 Cuisine_3 Cuisine_4
0        French, Japanese, Desserts    French  Japanese  Desserts       NaN
1                          Japanese  Japanese       NaN       NaN       NaN
2  Seafood, Asian, Filipino, Indian   Seafood     Asian  Filipino    Indian
3                   Japanese, Sushi  Japanese     Sushi       NaN       NaN
4                  Japanese, Korean  Japanese    Korean       NaN       NaN

In [2]:
import pandas as pd

df = pd.read_csv("../Dataset/zomato.csv", encoding="latin1")

country_df = pd.read_excel("../Dataset/country-code.xlsx")

df = df.merge(country_df, on="Country Code", how="left")

cuisine_split = df["Cuisines"].str.split(",", expand=True)

cuisine_split.columns = [
    f"Cuisine_{i+1}" for i in range(cuisine_split.shape[1])
]

cuisine_split = cuisine_split.apply(lambda x: x.str.strip())

df = pd.concat([df, cuisine_split], axis=1)

df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Votes,Country,Cuisine_1,Cuisine_2,Cuisine_3,Cuisine_4,Cuisine_5,Cuisine_6,Cuisine_7,Cuisine_8
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,314,Phillipines,French,Japanese,Desserts,NaN,NaN,NaN,NaN,NaN
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,591,Phillipines,Japanese,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,270,Phillipines,Seafood,Asian,Filipino,Indian,NaN,NaN,NaN,NaN
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,365,Phillipines,Japanese,Sushi,NaN,NaN,NaN,NaN,NaN,NaN
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,229,Phillipines,Japanese,Korean,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df["Aggregate rating"].dtype

dtype('float64')

In [4]:
df["Aggregate rating"].value_counts().sort_index()

Aggregate rating
0.0    2148
1.8       1
1.9       2
2.0       7
2.1      15
2.2      27
2.3      47
2.4      87
2.5     110
2.6     191
2.7     250
2.8     315
2.9     381
3.0     468
3.1     519
3.2     522
3.3     483
3.4     498
3.5     480
3.6     458
3.7     427
3.8     400
3.9     335
4.0     266
4.1     274
4.2     221
4.3     174
4.4     144
4.5      95
4.6      78
4.7      42
4.8      25
4.9      61
Name: count, dtype: int64

In [6]:
df["Aggregate rating"] = df["Aggregate rating"].replace(0.0, pd.NA)

In [7]:
df["Aggregate rating"].isna().sum()

np.int64(2148)

In [8]:
df["City"].value_counts().head(10)

City
New Delhi       5473
Gurgaon         1118
Noida           1080
Faridabad        251
Ghaziabad         25
Ahmedabad         21
Amritsar          21
Bhubaneshwar      21
Guwahati          21
Lucknow           21
Name: count, dtype: int64

In [9]:
df["Cuisine_1"].value_counts().head(10)

Cuisine_1
North Indian    2992
Chinese          855
Fast Food        672
Bakery           621
Cafe             617
American         278
South Indian     262
Mithai           246
Street Food      236
Continental      235
Name: count, dtype: int64

In [10]:
df["Average Cost for two"].describe()

count      9551.000000
mean       1199.210763
std       16121.183073
min           0.000000
25%         250.000000
50%         400.000000
75%         700.000000
max      800000.000000
Name: Average Cost for two, dtype: float64

In [11]:
df["Aggregate rating"].describe()

count     7403.0
unique      32.0
top          3.2
freq       522.0
Name: Aggregate rating, dtype: float64

In [14]:
df["Aggregate rating"] = pd.to_numeric(
    df["Aggregate rating"], errors="coerce"
)
df["Aggregate rating"].describe()

count    7403.000000
mean        3.440024
std         0.552195
min         1.800000
25%         3.000000
50%         3.400000
75%         3.800000
max         4.900000
Name: Aggregate rating, dtype: float64

In [15]:
df["Has Online delivery"].value_counts()

Has Online delivery
No     7100
Yes    2451
Name: count, dtype: int64

In [16]:
df["Has Table booking"].value_counts()

Has Table booking
No     8393
Yes    1158
Name: count, dtype: int64

In [17]:
df.shape

(9551, 30)

In [18]:
df[["Restaurant Name", "City", "Aggregate rating", "Average Cost for two"]].isnull().sum()

Restaurant Name            0
City                       0
Aggregate rating        2148
Average Cost for two       0
dtype: int64

In [19]:
df.to_csv("../Dataset/zomato_cleaned.csv", index=False)

In [21]:
pd.read_csv("../Dataset/zomato_cleaned.csv", encoding="latin1").shape

(9551, 30)

In [3]:
import csv

df.to_csv(
    "../Dataset/zomato_cleaned.csv",
    index=False,
    quoting=csv.QUOTE_ALL,
    lineterminator="\n"
)

In [4]:
pd.read_csv(
    "../Dataset/zomato_cleaned.csv",
    encoding="latin1"
).shape

(9551, 30)

In [5]:
df.to_excel("../Dataset/zomato_cleaned.xlsx", index=False)

In [6]:
pd.read_excel("../Dataset/zomato_cleaned.xlsx").shape

(9551, 30)